[platformio]
default_envs = esp32
src_dir = examples/uptime_post 

[common]
build_flags =
    -std=c++17
    -std=gnu++17
    -Wall
    -Wextra
    -Wformat
    -Wformat-security
    -Wpointer-arith
    -Werror=return-type
build_unflags =
    -std=gnu++11

[env:esp32]
platform = espressif32@7.0.1
board = lolin_d32
framework = arduino
lib_deps = file://src
lib_ldf_mode = deep+

build_flags = 
    ${common.build_flags}
    -D PIO_FRAMEWORK_ARDUINO_MAIN_ONLY
